name: Test PR

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Lint
        run: |
          npm install -g @angular/cli
          npm install
          npm run-script lint
      - name: Setup unifi instance
        run: |
          sudo apt-get update && sudo apt-get install ca-certificates apt-transport-https
          echo 'deb https://www.ui.com/downloads/unifi/debian stable ubiquiti' | sudo tee /etc/apt/sources.list.d/100-ubnt-unifi.list
          sudo wget -O /etc/apt/trusted.gpg.d/unifi-repo.gpg https://dl.ui.com/unifi/unifi-repo.gpg
          sudo apt-get install gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-mark hold openjdk-11-*
          sudo apt-get update && sudo apt-get install -y mongodb-org && sudo apt-get install unifi -y
          sudo service unifi start
      - name: Test
        run: |
          npm install -g @angular/cli
          npm install
          npm run-script test-headless
          npm run-script e2e
