name: Test and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Test
        run: |
          npm install -g @angular/cli
          npm install
          npm run-script test
          ./node_modules/.bin/codecov
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build
        run: |
          npm install -g @angular/cli
          npm install
          ng build --configuration production --base-href="/unifi-reset-password/"
      - name: Deploy
        if: "!contains(github.event.head_commit.message, 'skip-publish')"
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: dist/unifi-reset-password
          clean: true
